import React from 'react';

const RemindersView = () => {
    return (
        <div className="p-4">
            <h1 className="text-2xl font-bold">Reminders</h1>
            <p className="mt-4">This is the reminders view. Autogenerated reminders for jobs will be displayed here.</p>
        </div>
    );
};

export default RemindersView;